// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TB.AI.OKR.WebApp.Persistence.Contexts;

#nullable disable

namespace TB.AI.OKR.WebApp.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230903150239_RulesModified")]
    partial class RulesModified
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("OkrRuleReferenceSource", b =>
                {
                    b.Property<int>("OkrRulesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReferenceSourcesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OkrRulesId", "ReferenceSourcesId");

                    b.HasIndex("ReferenceSourcesId");

                    b.ToTable("OkrRuleReferenceSource");
                });

            modelBuilder.Entity("TB.AI.OKR.WebApp.Persistence.Entities.KeyResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ObjectiveId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ObjectiveId");

                    b.ToTable("KeyResults");
                });

            modelBuilder.Entity("TB.AI.OKR.WebApp.Persistence.Entities.Objective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("IsArchievableRating")
                        .HasColumnType("REAL");

                    b.Property<double>("IsMeasurableRating")
                        .HasColumnType("REAL");

                    b.Property<double>("IsRelevantRating")
                        .HasColumnType("REAL");

                    b.Property<double>("IsSpecificRating")
                        .HasColumnType("REAL");

                    b.Property<double>("IsTimeBoundedRating")
                        .HasColumnType("REAL");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Objectives");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Objective");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TB.AI.OKR.WebApp.Persistence.Entities.OkrRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("OkrRules");

                    b.HasData(
                        new
                        {
                            Id = 19,
                            Description = "have excactly one objective",
                            Scope = 1,
                            Severity = 2
                        },
                        new
                        {
                            Id = 20,
                            Description = "have not more than 5 key results",
                            Scope = 1,
                            Severity = 1
                        },
                        new
                        {
                            Id = 21,
                            Description = "have at least 1 key result",
                            Scope = 1,
                            Severity = 2
                        },
                        new
                        {
                            Id = 22,
                            Description = "have at least 3 key results",
                            Scope = 1,
                            Severity = 1
                        },
                        new
                        {
                            Id = 23,
                            Description = "can be abbreviated with O",
                            Scope = 2,
                            Severity = 0
                        },
                        new
                        {
                            Id = 24,
                            Description = "describes the \"What\"",
                            Scope = 2,
                            Severity = 0
                        },
                        new
                        {
                            Id = 25,
                            Description = "expresses goals or intends",
                            Scope = 2,
                            Severity = 0
                        },
                        new
                        {
                            Id = 26,
                            Description = "be aggressive, yet realistic",
                            Scope = 2,
                            Severity = 1
                        },
                        new
                        {
                            Id = 27,
                            Description = "be tangible, objective, and unambigous",
                            Scope = 2,
                            Severity = 1
                        },
                        new
                        {
                            Id = 28,
                            Description = "be obvious to a rational observer whether an objective has been achieved",
                            Scope = 2,
                            Severity = 1
                        },
                        new
                        {
                            Id = 29,
                            Description = "provide clear value to the company when successful achieved",
                            Scope = 2,
                            Severity = 2
                        },
                        new
                        {
                            Id = 30,
                            Description = "can be abbreviated with KR",
                            Scope = 3,
                            Severity = 0
                        },
                        new
                        {
                            Id = 31,
                            Description = "describes the \"How\"",
                            Scope = 3,
                            Severity = 0
                        },
                        new
                        {
                            Id = 32,
                            Description = "express measurable outcome",
                            Scope = 3,
                            Severity = 0
                        },
                        new
                        {
                            Id = 33,
                            Description = "express an outcome instead an output",
                            Scope = 3,
                            Severity = 1
                        },
                        new
                        {
                            Id = 34,
                            Description = "describe outcome, not activities (if words like consult, help, analyze, or participate are included, it describes activities)",
                            Scope = 3,
                            Severity = 1
                        },
                        new
                        {
                            Id = 35,
                            Description = "measurable and verifiable",
                            Scope = 3,
                            Severity = 1
                        },
                        new
                        {
                            Id = 36,
                            Description = "be difficult but not impossible to achieve",
                            Scope = 3,
                            Severity = 1
                        });
                });

            modelBuilder.Entity("TB.AI.OKR.WebApp.Persistence.Entities.ReferenceSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Authors")
                        .HasColumnType("TEXT");

                    b.Property<string>("DOI")
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReferenceSourceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("URL")
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ReferenceSources");
                });

            modelBuilder.Entity("TB.AI.OKR.WebApp.Persistence.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("ReviewTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SampleOkrId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SampleOkrId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("TB.AI.OKR.WebApp.Persistence.Entities.SampleOkr", b =>
                {
                    b.HasBaseType("TB.AI.OKR.WebApp.Persistence.Entities.Objective");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("SampleOkr");
                });

            modelBuilder.Entity("OkrRuleReferenceSource", b =>
                {
                    b.HasOne("TB.AI.OKR.WebApp.Persistence.Entities.OkrRule", null)
                        .WithMany()
                        .HasForeignKey("OkrRulesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TB.AI.OKR.WebApp.Persistence.Entities.ReferenceSource", null)
                        .WithMany()
                        .HasForeignKey("ReferenceSourcesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TB.AI.OKR.WebApp.Persistence.Entities.KeyResult", b =>
                {
                    b.HasOne("TB.AI.OKR.WebApp.Persistence.Entities.Objective", null)
                        .WithMany("KeyResults")
                        .HasForeignKey("ObjectiveId");
                });

            modelBuilder.Entity("TB.AI.OKR.WebApp.Persistence.Entities.Review", b =>
                {
                    b.HasOne("TB.AI.OKR.WebApp.Persistence.Entities.SampleOkr", null)
                        .WithMany("Reviews")
                        .HasForeignKey("SampleOkrId");
                });

            modelBuilder.Entity("TB.AI.OKR.WebApp.Persistence.Entities.Objective", b =>
                {
                    b.Navigation("KeyResults");
                });

            modelBuilder.Entity("TB.AI.OKR.WebApp.Persistence.Entities.SampleOkr", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
